global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "saffira_backend"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:3000"]

rule_files:
  - /etc/prometheus/rules/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
